export const TIME_CONFIG = {
  GLOBAL_MIN_SECONDS: 30,
  GLOBAL_MAX_SECONDS: 120,
  PRACTICE_MIN_SECONDS: 30,
  PRACTICE_MAX_SECONDS: 120,
  PVP_FIXED_SECONDS: 60,
  PVP_MAX_SECONDS: 60,
};

export const INVENTORY_CONFIG = {
  MINIMUM_THRESHOLD_PER_SUBTOPIC: 20,
  TARGET_THRESHOLD_PER_SUBTOPIC: 30,
  DEFAULT_BATCH_GENERATION_UNIT: 10,
  PRACTICE_DIFFICULTY_DISTRIBUTION: {
    EASY: 5,
    MEDIUM: 4,
    HARD: 1,
  },
  PVP_DIFFICULTY_CONFIG: {
    EASY_WEIGHT: 0.33,
    MEDIUM_WEIGHT: 0.34,
    HARD_WEIGHT: 0.33,
  },
  LOCK_TTL_SECONDS: 60, // Distributed lock TTL in Redis
  PRACTICE_SESSION_QUESTIONS_COUNT: 10,
  PVP_SET_QUESTIONS_COUNT: 10,
};
